wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1667195778.225228
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.13
      5: 0.13.4
      8:
      - 5
batch_size:
  desc: null
  value: 64
criterion:
  desc: null
  value: cross_entropy
epochs:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: Adam
resize:
  desc: null
  value:
  - 224
  - 224
